In [0]:
TP STANDARDSCALER FROM SCRATCH

In [ ]:
Créer une class StandardScaler2 avec comme méthode fit, transform, fit_transform et en attribut un dicitonnaire params_ qui contient la moyenne et l'écart_type de vos données. Les données en entrées sont uniquement de array numpy (pas des dataframes)
me dire que vous avez terminé avant de faire le bonus.
en bonus :
- mettre une erreur si on essaye de transform sans avoir de fit
- permettre au code de fonctionner, peut importe si l'entrée est une numpy array ou une dataframe


In [0]:
import numpy as np

X = np.array([[1, 2, 53],
             [91, 2, 7],
             [1, 82, 33],])



        

In [0]:
class StandardScaler2:
  def __init__(self,array_num):
        self.array_num = array_num
  
        self.params_ = {}

  def fit(self):
    for i in range(1, len(self.array_num)):
      self.moyennes_colonnes = np.mean(X[:,i])
      self.ecart_types = np.std(X[:,i])
      self.params_[f'moyenne_colonne{i}'] = self.moyennes_colonnes
      self.params_[f'ecart-type_colonne{i}'] = self.ecart_types
    return self.moyennes_colonnes, self.ecart_types

    
  def transform(self):
    for i in range(len(self.array_num)):
      for a in self.array_num[:,i]:
        print(a)
        self.result_2 = (a - (self.params_[f'moyenne_colonne{i}']) / (self.params_[f'ecart-type_colonne{i}']) )
        #self.result =  (self.array_num -(np.mean(X[:,i]))) / (np.std(X[:,i]))
    #return self.result_2

  def fit_transform(self):
    return self.transform()

In [0]:
X_transform = StandardScaler2(X)

In [125]:
X_transform.fit()

(31.0, 18.83259585576738)

In [126]:
X_transform.params_

{'ecart-type_colonne1': 37.71236166328253,
 'ecart-type_colonne2': 18.83259585576738,
 'moyenne_colonne1': 28.666666666666668,
 'moyenne_colonne2': 31.0}

In [127]:
X_transform.transform()

1


KeyError: ignored

In [51]:
X_transform.fit_transform()

array([[-1.59298273, -1.53988331,  1.16818734],
       [ 3.18596546, -1.53988331, -1.27438619],
       [-1.59298273,  2.70807064,  0.10619885]])

In [ ]:
2EME CLASSE

In [0]:
class StandardScaler_2:
  def __init__(self,array_num):
        self.array_num = array_num
  
        self.params_ = {}

  def fit(self, array_num):
    for i in range(len(self.array_num)):
      self.params_[f'moyenne_colonne-{i}'] = np.mean(X[:,i])
      self.params_[f'ecart-type_colonne-{i}'] = np.std(X[:,i])
    return self

  def transform(self, array_num):
    for i in range(len(self.array_num)):
      self.result =  (self.array_num -(np.mean(X[:,i]))) / (np.std(X[:,i]))
    return self.result

  def fit_transform(self, array_num):
    return self.fit(array_num).transform(array_num)

In [0]:
X_transform1 = StandardScaler_2(X)

In [136]:
X_transform1.fit(X)

In [139]:
X_transform1.params_

{'ecart-type_colonne-0': 42.42640687119285,
 'ecart-type_colonne-1': 37.71236166328253,
 'ecart-type_colonne-2': 18.83259585576738,
 'moyenne_colonne-0': 31.0,
 'moyenne_colonne-1': 28.666666666666668,
 'moyenne_colonne-2': 31.0}

In [140]:
X_transform1.transform(X)

array([[-1.59298273, -1.53988331,  1.16818734],
       [ 3.18596546, -1.53988331, -1.27438619],
       [-1.59298273,  2.70807064,  0.10619885]])

In [141]:
X_transform1.fit_transform(X)

array([[-1.59298273, -1.53988331,  1.16818734],
       [ 3.18596546, -1.53988331, -1.27438619],
       [-1.59298273,  2.70807064,  0.10619885]])